/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.kat.avropossimulator.model;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class DeliveryAddress extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -630666380341911164L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"DeliveryAddress\",\"namespace\":\"com.kat.avropossimulator.model\",\"fields\":[{\"name\":\"address_line\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}]},{\"name\":\"city\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}]},{\"name\":\"country\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}]},{\"name\":\"post_code\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}]},{\"name\":\"contact_number\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<DeliveryAddress> ENCODER =
      new BinaryMessageEncoder<DeliveryAddress>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<DeliveryAddress> DECODER =
      new BinaryMessageDecoder<DeliveryAddress>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<DeliveryAddress> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<DeliveryAddress> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<DeliveryAddress> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<DeliveryAddress>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this DeliveryAddress to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a DeliveryAddress from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a DeliveryAddress instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static DeliveryAddress fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.String address_line;
  private java.lang.String city;
  private java.lang.String country;
  private java.lang.String post_code;
  private java.lang.String contact_number;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public DeliveryAddress() {}

  /**
   * All-args constructor.
   * @param address_line The new value for address_line
   * @param city The new value for city
   * @param country The new value for country
   * @param post_code The new value for post_code
   * @param contact_number The new value for contact_number
   */
  public DeliveryAddress(java.lang.String address_line, java.lang.String city, java.lang.String country, java.lang.String post_code, java.lang.String contact_number) {
    this.address_line = address_line;
    this.city = city;
    this.country = country;
    this.post_code = post_code;
    this.contact_number = contact_number;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return address_line;
    case 1: return city;
    case 2: return country;
    case 3: return post_code;
    case 4: return contact_number;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: address_line = value$ != null ? value$.toString() : null; break;
    case 1: city = value$ != null ? value$.toString() : null; break;
    case 2: country = value$ != null ? value$.toString() : null; break;
    case 3: post_code = value$ != null ? value$.toString() : null; break;
    case 4: contact_number = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'address_line' field.
   * @return The value of the 'address_line' field.
   */
  public java.lang.String getAddressLine() {
    return address_line;
  }


  /**
   * Sets the value of the 'address_line' field.
   * @param value the value to set.
   */
  public void setAddressLine(java.lang.String value) {
    this.address_line = value;
  }

  /**
   * Gets the value of the 'city' field.
   * @return The value of the 'city' field.
   */
  public java.lang.String getCity() {
    return city;
  }


  /**
   * Sets the value of the 'city' field.
   * @param value the value to set.
   */
  public void setCity(java.lang.String value) {
    this.city = value;
  }

  /**
   * Gets the value of the 'country' field.
   * @return The value of the 'country' field.
   */
  public java.lang.String getCountry() {
    return country;
  }


  /**
   * Sets the value of the 'country' field.
   * @param value the value to set.
   */
  public void setCountry(java.lang.String value) {
    this.country = value;
  }

  /**
   * Gets the value of the 'post_code' field.
   * @return The value of the 'post_code' field.
   */
  public java.lang.String getPostCode() {
    return post_code;
  }


  /**
   * Sets the value of the 'post_code' field.
   * @param value the value to set.
   */
  public void setPostCode(java.lang.String value) {
    this.post_code = value;
  }

  /**
   * Gets the value of the 'contact_number' field.
   * @return The value of the 'contact_number' field.
   */
  public java.lang.String getContactNumber() {
    return contact_number;
  }


  /**
   * Sets the value of the 'contact_number' field.
   * @param value the value to set.
   */
  public void setContactNumber(java.lang.String value) {
    this.contact_number = value;
  }

  /**
   * Creates a new DeliveryAddress RecordBuilder.
   * @return A new DeliveryAddress RecordBuilder
   */
  public static com.kat.avropossimulator.model.DeliveryAddress.Builder newBuilder() {
    return new com.kat.avropossimulator.model.DeliveryAddress.Builder();
  }

  /**
   * Creates a new DeliveryAddress RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new DeliveryAddress RecordBuilder
   */
  public static com.kat.avropossimulator.model.DeliveryAddress.Builder newBuilder(com.kat.avropossimulator.model.DeliveryAddress.Builder other) {
    if (other == null) {
      return new com.kat.avropossimulator.model.DeliveryAddress.Builder();
    } else {
      return new com.kat.avropossimulator.model.DeliveryAddress.Builder(other);
    }
  }

  /**
   * Creates a new DeliveryAddress RecordBuilder by copying an existing DeliveryAddress instance.
   * @param other The existing instance to copy.
   * @return A new DeliveryAddress RecordBuilder
   */
  public static com.kat.avropossimulator.model.DeliveryAddress.Builder newBuilder(com.kat.avropossimulator.model.DeliveryAddress other) {
    if (other == null) {
      return new com.kat.avropossimulator.model.DeliveryAddress.Builder();
    } else {
      return new com.kat.avropossimulator.model.DeliveryAddress.Builder(other);
    }
  }

  /**
   * RecordBuilder for DeliveryAddress instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<DeliveryAddress>
    implements org.apache.avro.data.RecordBuilder<DeliveryAddress> {

    private java.lang.String address_line;
    private java.lang.String city;
    private java.lang.String country;
    private java.lang.String post_code;
    private java.lang.String contact_number;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.kat.avropossimulator.model.DeliveryAddress.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.address_line)) {
        this.address_line = data().deepCopy(fields()[0].schema(), other.address_line);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.city)) {
        this.city = data().deepCopy(fields()[1].schema(), other.city);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.country)) {
        this.country = data().deepCopy(fields()[2].schema(), other.country);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.post_code)) {
        this.post_code = data().deepCopy(fields()[3].schema(), other.post_code);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.contact_number)) {
        this.contact_number = data().deepCopy(fields()[4].schema(), other.contact_number);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
    }

    /**
     * Creates a Builder by copying an existing DeliveryAddress instance
     * @param other The existing instance to copy.
     */
    private Builder(com.kat.avropossimulator.model.DeliveryAddress other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.address_line)) {
        this.address_line = data().deepCopy(fields()[0].schema(), other.address_line);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.city)) {
        this.city = data().deepCopy(fields()[1].schema(), other.city);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.country)) {
        this.country = data().deepCopy(fields()[2].schema(), other.country);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.post_code)) {
        this.post_code = data().deepCopy(fields()[3].schema(), other.post_code);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.contact_number)) {
        this.contact_number = data().deepCopy(fields()[4].schema(), other.contact_number);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'address_line' field.
      * @return The value.
      */
    public java.lang.String getAddressLine() {
      return address_line;
    }


    /**
      * Sets the value of the 'address_line' field.
      * @param value The value of 'address_line'.
      * @return This builder.
      */
    public com.kat.avropossimulator.model.DeliveryAddress.Builder setAddressLine(java.lang.String value) {
      validate(fields()[0], value);
      this.address_line = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'address_line' field has been set.
      * @return True if the 'address_line' field has been set, false otherwise.
      */
    public boolean hasAddressLine() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'address_line' field.
      * @return This builder.
      */
    public com.kat.avropossimulator.model.DeliveryAddress.Builder clearAddressLine() {
      address_line = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'city' field.
      * @return The value.
      */
    public java.lang.String getCity() {
      return city;
    }


    /**
      * Sets the value of the 'city' field.
      * @param value The value of 'city'.
      * @return This builder.
      */
    public com.kat.avropossimulator.model.DeliveryAddress.Builder setCity(java.lang.String value) {
      validate(fields()[1], value);
      this.city = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'city' field has been set.
      * @return True if the 'city' field has been set, false otherwise.
      */
    public boolean hasCity() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'city' field.
      * @return This builder.
      */
    public com.kat.avropossimulator.model.DeliveryAddress.Builder clearCity() {
      city = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'country' field.
      * @return The value.
      */
    public java.lang.String getCountry() {
      return country;
    }


    /**
      * Sets the value of the 'country' field.
      * @param value The value of 'country'.
      * @return This builder.
      */
    public com.kat.avropossimulator.model.DeliveryAddress.Builder setCountry(java.lang.String value) {
      validate(fields()[2], value);
      this.country = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'country' field has been set.
      * @return True if the 'country' field has been set, false otherwise.
      */
    public boolean hasCountry() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'country' field.
      * @return This builder.
      */
    public com.kat.avropossimulator.model.DeliveryAddress.Builder clearCountry() {
      country = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'post_code' field.
      * @return The value.
      */
    public java.lang.String getPostCode() {
      return post_code;
    }


    /**
      * Sets the value of the 'post_code' field.
      * @param value The value of 'post_code'.
      * @return This builder.
      */
    public com.kat.avropossimulator.model.DeliveryAddress.Builder setPostCode(java.lang.String value) {
      validate(fields()[3], value);
      this.post_code = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'post_code' field has been set.
      * @return True if the 'post_code' field has been set, false otherwise.
      */
    public boolean hasPostCode() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'post_code' field.
      * @return This builder.
      */
    public com.kat.avropossimulator.model.DeliveryAddress.Builder clearPostCode() {
      post_code = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'contact_number' field.
      * @return The value.
      */
    public java.lang.String getContactNumber() {
      return contact_number;
    }


    /**
      * Sets the value of the 'contact_number' field.
      * @param value The value of 'contact_number'.
      * @return This builder.
      */
    public com.kat.avropossimulator.model.DeliveryAddress.Builder setContactNumber(java.lang.String value) {
      validate(fields()[4], value);
      this.contact_number = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'contact_number' field has been set.
      * @return True if the 'contact_number' field has been set, false otherwise.
      */
    public boolean hasContactNumber() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'contact_number' field.
      * @return This builder.
      */
    public com.kat.avropossimulator.model.DeliveryAddress.Builder clearContactNumber() {
      contact_number = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public DeliveryAddress build() {
      try {
        DeliveryAddress record = new DeliveryAddress();
        record.address_line = fieldSetFlags()[0] ? this.address_line : (java.lang.String) defaultValue(fields()[0]);
        record.city = fieldSetFlags()[1] ? this.city : (java.lang.String) defaultValue(fields()[1]);
        record.country = fieldSetFlags()[2] ? this.country : (java.lang.String) defaultValue(fields()[2]);
        record.post_code = fieldSetFlags()[3] ? this.post_code : (java.lang.String) defaultValue(fields()[3]);
        record.contact_number = fieldSetFlags()[4] ? this.contact_number : (java.lang.String) defaultValue(fields()[4]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<DeliveryAddress>
    WRITER$ = (org.apache.avro.io.DatumWriter<DeliveryAddress>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<DeliveryAddress>
    READER$ = (org.apache.avro.io.DatumReader<DeliveryAddress>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    if (this.address_line == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.address_line);
    }

    if (this.city == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.city);
    }

    if (this.country == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.country);
    }

    if (this.post_code == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.post_code);
    }

    if (this.contact_number == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.contact_number);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (in.readIndex() != 1) {
        in.readNull();
        this.address_line = null;
      } else {
        this.address_line = in.readString();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.city = null;
      } else {
        this.city = in.readString();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.country = null;
      } else {
        this.country = in.readString();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.post_code = null;
      } else {
        this.post_code = in.readString();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.contact_number = null;
      } else {
        this.contact_number = in.readString();
      }

    } else {
      for (int i = 0; i < 5; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (in.readIndex() != 1) {
            in.readNull();
            this.address_line = null;
          } else {
            this.address_line = in.readString();
          }
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.city = null;
          } else {
            this.city = in.readString();
          }
          break;

        case 2:
          if (in.readIndex() != 1) {
            in.readNull();
            this.country = null;
          } else {
            this.country = in.readString();
          }
          break;

        case 3:
          if (in.readIndex() != 1) {
            in.readNull();
            this.post_code = null;
          } else {
            this.post_code = in.readString();
          }
          break;

        case 4:
          if (in.readIndex() != 1) {
            in.readNull();
            this.contact_number = null;
          } else {
            this.contact_number = in.readString();
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










